# Generated by Django 4.2.2 on 2023-09-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuserpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserPermission',
        ),
    ]
