# Generated by Django 4.2.2 on 2023-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0005_usergameentry_delete_usergamelist'),
        ('users', '0002_profile_game_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game_list',
            field=models.ManyToManyField(blank=True, to='gameslist.usergameentry'),
        ),
    ]
