# Generated by Django 4.2.2 on 2023-06-21 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gender_alter_user_date_created_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='motto',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 14, 57, 53, 699250, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 14, 57, 53, 699250, tzinfo=datetime.timezone.utc)),
        ),
    ]
