# Generated by Django 4.2.2 on 2023-09-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_delete_customuserpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPermission',
            fields=[
                ('permission', models.OneToOneField(limit_choices_to={'codename': 'custom admin'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Admin Permissions',
                'verbose_name_plural': 'Admin Permissions',
            },
        ),
    ]
