# Generated by Django 4.2.2 on 2023-08-16 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangalist', '0002_mangalist_orginal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangalist',
            name='orginal_slug',
        ),
        migrations.AlterField(
            model_name='raiting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manga_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='value',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
