# Generated by Django 4.2.2 on 2023-09-24 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gameslist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentRaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_rating', models.CharField(choices=[('like', 'like'), ('heart', 'heart'), ('surprise', 'surprise'), ('laugh', 'laugh'), ('trash', 'trash')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(default=gameslist.models.get_default_founder_avatar, upload_to='founder_photos/')),
                ('founder_slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='company_logo/')),
                ('description', models.TextField(blank=True, null=True)),
                ('established_date', models.DateField()),
                ('developer_slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_version', models.CharField(choices=[('alpha', 'alpha'), ('beta', 'beta'), ('early access', 'early access'), ('full release', 'full release')], max_length=30)),
                ('game_mode', models.CharField(choices=[('single-player', 'single-player'), ('online PvP', 'online PvP'), ('online co-op', 'online co-op'), ('cross-platform multiplayer', 'cross-platform multiplayer')], max_length=30)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('trailer', models.URLField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='game/cover/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('public', 'public')], max_length=100)),
                ('game_slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(default=gameslist.models.get_default_founder_avatar, upload_to='platform_photos/')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('platform_slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(default=gameslist.models.get_default_founder_avatar, upload_to='founder_photos/')),
                ('platform_creator_slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamePublisher',
            fields=[
                ('gamedeveloper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gameslist.gamedeveloper')),
            ],
            bases=('gameslist.gamedeveloper',),
        ),
        migrations.CreateModel(
            name='UserGameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('playing', 'playing'), ('completed', 'completed'), ('on hold', 'on hold'), ('dropped', 'dropped'), ('plan to play', 'plan to play')], default='plan to play', max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('added_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gameslist.gamelist')),
            ],
        ),
    ]
