# Generated by Django 4.2.2 on 2023-08-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('plaing', 'plaing'), ('comleted', 'comleted'), ('on hold', 'on hold'), ('dropped', 'dropped'), ('plan to play', 'plan to play')], max_length=100)),
            ],
        ),
    ]
