# Generated by Django 4.2.2 on 2023-10-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='game_mode',
            field=models.CharField(blank=True, choices=[('single-player', 'single-player'), ('online PvP', 'online PvP'), ('online co-op', 'online co-op'), ('cross-platform multiplayer', 'cross-platform multiplayer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='game_version',
            field=models.CharField(blank=True, choices=[('alpha', 'alpha'), ('beta', 'beta'), ('early access', 'early access'), ('full release', 'full release')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('public', 'public')], default='pending', max_length=100),
        ),
    ]
