# Generated by Django 4.2.2 on 2023-08-26 19:37

from django.db import migrations, models
import gameslist.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='founder',
            name='photo',
            field=models.ImageField(default=gameslist.models.get_default_founder_avatar, upload_to='founder_photos/'),
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='founders',
            field=models.ManyToManyField(blank=True, to='gameslist.founder'),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gameslist.tag'),
        ),
    ]
