# Generated by Django 4.2.2 on 2023-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcreator',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
