# Generated by Django 4.2.2 on 2023-09-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='game_mode',
            field=models.CharField(choices=[('single-player', 'single-player'), ('online PvP', 'online PvP'), ('online co-op', 'online co-op'), ('cross-platform multiplayer', 'cross-platform multiplayer')], default=True, max_length=30),
            preserve_default=False,
        ),
    ]
