# Generated by Django 4.2.2 on 2023-09-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gameslist.gamedeveloper'),
        ),
    ]
