# Generated by Django 4.2.2 on 2023-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0003_alter_platformcreator_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
