# Generated by Django 4.2.2 on 2023-09-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0003_gamelist_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='game_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_publisher', to='gameslist.gamepublisher'),
        ),
    ]
