# Generated by Django 4.2.2 on 2023-08-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0003_tag_alter_founder_photo_alter_gamedeveloper_founders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='gamelist',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='gameslist.platform'),
        ),
    ]
