# Generated by Django 4.2.2 on 2023-08-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0003_alter_rating_user_usergamelist_games_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergamelist',
            name='user',
        ),
    ]
