# Generated by Django 4.2.2 on 2023-10-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0003_alter_gamedeveloper_established_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamelist',
            name='game_mode',
        ),
        migrations.AddField(
            model_name='gamelist',
            name='game_mode',
            field=models.ManyToManyField(blank=True, null=True, to='gameslist.gamemode'),
        ),
    ]
