# Generated by Django 4.2.2 on 2023-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0003_alter_gamelist_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='game_type',
            field=models.ManyToManyField(blank=True, to='gameslist.type'),
        ),
    ]
