# Generated by Django 4.2.2 on 2023-10-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0004_gamemode_remove_gamelist_game_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='game_mode',
            field=models.ManyToManyField(to='gameslist.gamemode'),
        ),
    ]
