# Generated by Django 4.2.2 on 2023-09-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0004_alter_gamelist_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='category',
            field=models.ManyToManyField(null=True, to='gameslist.category'),
        ),
    ]
