# Generated by Django 4.2.2 on 2023-08-21 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_game_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameslist', '0004_remove_usergamelist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('plaing', 'plaing'), ('comleted', 'comleted'), ('on hold', 'on hold'), ('dropped', 'dropped'), ('plan to play', 'plan to play')], default='plan to play', max_length=100)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gameslist.gamelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserGameList',
        ),
    ]
