# Generated by Django 4.2.2 on 2023-08-27 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameslist', '0004_alter_platform_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelist',
            old_name='author',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='gamelist',
            old_name='video',
            new_name='trailer',
        ),
        migrations.AlterUniqueTogether(
            name='commentraiting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commentraiting',
            name='comment_rating',
            field=models.CharField(choices=[('like', 'like'), ('heart', 'heart'), ('surprise', 'surprise'), ('laugh', 'laugh'), ('trash', 'trash')], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamelist',
            name='game_version',
            field=models.CharField(choices=[('alpha', 'alpha'), ('beta', 'beta'), ('early access', 'early access'), ('full release', 'full release')], default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='commentraiting',
            unique_together={('user', 'comment', 'comment_rating')},
        ),
        migrations.RemoveField(
            model_name='commentraiting',
            name='comment_raiting',
        ),
    ]
