# Generated by Django 4.2.2 on 2023-08-23 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0005_usergameentry_delete_usergamelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergameentry',
            name='added_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='usergameentry',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergameentry',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usergameentry',
            name='status',
            field=models.CharField(choices=[('playing', 'playing'), ('comleted', 'comleted'), ('on hold', 'on hold'), ('dropped', 'dropped'), ('plan to play', 'plan to play')], default='plan to play', max_length=100),
        ),
    ]
