# Generated by Django 4.2.2 on 2023-09-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0005_rename_author_gamelist_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
