# Generated by Django 4.2.2 on 2023-09-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0006_alter_gamelist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
