# Generated by Django 4.2.2 on 2023-08-23 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0006_usergameentry_added_date_usergameentry_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergameentry',
            name='added_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usergameentry',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergameentry',
            name='status',
            field=models.CharField(choices=[('playing', 'playing'), ('completed', 'completed'), ('on hold', 'on hold'), ('dropped', 'dropped'), ('plan to play', 'plan to play')], default='plan to play', max_length=100),
        ),
    ]
