# Generated by Django 4.2.2 on 2023-11-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0006_alter_gamelist_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedeveloper',
            name='established_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
