# Generated by Django 4.2.2 on 2023-11-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0007_alter_gamedeveloper_established_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('direct_x', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('sound_card', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gamelist',
            name='highest_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_with_high_req', to='gameslist.hardwarerequirements'),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='minimum_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_with_min_req', to='gameslist.hardwarerequirements'),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='recommended_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_with_rec_req', to='gameslist.hardwarerequirements'),
        ),
    ]
