# Generated by Django 4.2.2 on 2023-08-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0007_alter_usergameentry_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergameentry',
            name='rating',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.PROTECT, to='gameslist.rating'),
            preserve_default=False,
        ),
    ]
