# Generated by Django 4.2.2 on 2023-12-03 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameslist', '0008_hardwarerequirements_gamelist_highest_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_games_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
