# Generated by Django 4.2.2 on 2023-08-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0008_usergameentry_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergameentry',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gameslist.rating'),
        ),
    ]
