# Generated by Django 4.2.2 on 2023-12-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0009_gamelist_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelist',
            name='category',
        ),
        migrations.AddField(
            model_name='gamelist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gameslist.category'),
        ),
    ]
