# Generated by Django 4.2.2 on 2023-08-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0009_alter_usergameentry_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergameentry',
            name='notes',
        ),
        migrations.AddField(
            model_name='usergameentry',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
