# Generated by Django 4.2.2 on 2023-08-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0010_remove_usergameentry_notes_usergameentry_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergameentry',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
