# Generated by Django 4.2.2 on 2023-09-24 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animelist',
            name='anime_type',
            field=models.ManyToManyField(to='animelist.type'),
        ),
        migrations.AddField(
            model_name='animelist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animelist',
            name='category',
            field=models.ManyToManyField(to='animelist.category'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('anime', 'user')},
        ),
    ]
