# Generated by Django 4.2.2 on 2023-08-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='anime/cover/'),
        ),
    ]
