# Generated by Django 4.2.2 on 2023-09-24 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoplan',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todoplan',
            name='todo',
            field=models.ManyToManyField(blank=True, to='todo.todo'),
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(blank=True, to='todo.todocategory'),
        ),
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.ManyToManyField(blank=True, to='todo.task'),
        ),
    ]
