# Generated by Django 4.2.2 on 2023-06-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.ManyToManyField(blank=True, null=True, to='todo.task'),
        ),
    ]
