# Generated by Django 4.2.2 on 2023-06-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='todoplan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
