# Generated by Django 4.2.2 on 2023-07-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_options_alter_todo_options_todoplan_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='cos',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
