# Generated by Django 4.2.2 on 2023-07-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_options_alter_todo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='cos',
            new_name='completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
