# Generated by Django 4.2.2 on 2023-07-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_cos_todo_completed_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(blank=True, to='todo.todocategory'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.ManyToManyField(blank=True, to='todo.task'),
        ),
    ]
