# Generated by Django 4.2.2 on 2023-08-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_category_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoplan',
            name='todo',
            field=models.ManyToManyField(blank=True, to='todo.todo'),
        ),
    ]
