# Generated by Django 4.2.2 on 2023-09-24 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookslist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookslist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookslist',
            name='books_type',
            field=models.ManyToManyField(to='bookslist.type'),
        ),
        migrations.AddField(
            model_name='bookslist',
            name='category',
            field=models.ManyToManyField(to='bookslist.category'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('books', 'user')},
        ),
    ]
